name: biometrics_demo
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  local_auth: ^2.3.0
  fluttertoast: ^8.2.12


  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.1.0
  nb_utils: ^7.1.4
  latlong2: ^0.9.1
  flutter_map: ^8.1.1
  geolocator: ^14.0.0
  permission_handler: ^12.0.0+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/lang/en.json
    - assets/lang/ar.json
    - assets/images/
